# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ur_on_linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    linear_guide_string_velocity_position_controller:
      type: string_velocity_position_controller/StringVelocityPositionController
      
linear_guide_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    
ur_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

ur_on_linear_guide_controller:
  ros__parameters:
    joints:
      - guide_linear_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true  