controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    fr3_arm_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    fr3_gripper:
      type: position_controllers/GripperActionController

franka_robot_state_broadcaster:
  ros__parameters:
    lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
    lock_sleep_interval: 5 # microseconds sleep between attempts
    lock_log_error: false #  Log error if lock acquisition fails - false == do not log  
    lock_update_success: true # return update OK, although lock fails (no update occurs)

    
fr3_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
      #- effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    gains:
      fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
      fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
      fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

fr3_arm_scaled_controller:
  ros__parameters:
    joints: 
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
      fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
      fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["safe_ovr","speed_ovr"]
    allow_nonzero_velocity_at_trajectory_end: false


fr3_gripper:
  ros__parameters:
    action_monitor_rate: 20.0 # Hz
    joint: fr3_finger_joint1
    max_effort: 10.0 # N
    goal_tolerance: 0.01 # m
    allow_stalling: true
    stall_velocity_threshold: 0.001 #m/s
    stall_timeout: 1.0 # s
    state_interfaces:
      - position