# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  fr3_joint1:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 87.0
    max_position: 2.7437
    max_velocity: 2.62
    min_position: -2.7437

  fr3_joint2:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 87.0
    max_position: 1.7837
    max_velocity: 2.62
    min_position: -1.7837
  
  fr3_joint3:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 87.0
    max_position: 2.9007
    max_velocity: 2.62
    min_position: -2.9007

  fr3_joint4:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 87.0
    max_position: -0.1518
    max_velocity: 2.62
    min_position: -3.0421

  fr3_joint5:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 2.8065
    max_velocity: 5.26
    min_position: -2.8065

  fr3_joint6:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 4.5169
    max_velocity: 4.18
    min_position: 0.5445

  fr3_joint7:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true 
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 3.0159
    max_velocity: 5.26
    min_position: -3.0159


########################################
fr3_joint1:
  limit:
    lower:      -2.7437
    upper:       2.7437
    velocity:    2.62
    effort:     87.0

fr3_joint2:
  limit:
    lower:     -1.7837
    upper:      1.7837
    velocity:   2.62
    effort:    87.0

fr3_joint3:
  limit:
    lower:     -2.9007
    upper:      2.9007
    velocity:   2.62
    effort:    87.0

fr3_joint4:
  limit:
    lower:     -3.0421
    upper:     -0.1518
    velocity:   2.62
    effort:    87.0

fr3_joint5:
  limit:
    lower:     -2.8065
    upper:      2.8065
    velocity:   5.26
    effort:    12.0

fr3_joint6:
  limit:
    lower:      0.5445
    upper:      4.5169
    velocity:   4.18
    effort:    12.0

fr3_joint7:
  limit:
    lower:     -3.0159
    upper:      3.0159
    velocity:   5.26
    effort:    12.0
