fr3_arm:  
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001

fr3_joint1:
  kinematic:
    x: 0
    y: 0
    z: 0.333
    roll: 0
    pitch: 0
    yaw: 0

fr3_joint2:
  kinematic:
    x: 0
    y: 0
    z: 0
    roll: -1.570796326794897
    pitch: 0
    yaw: 0

fr3_joint3:
  kinematic:
    x: 0
    y: -0.316
    z: 0
    roll: 1.570796326794897
    pitch: 0
    yaw: 0

fr3_joint4:
  kinematic:
    x: 0.0825
    y: 0
    z: 0
    roll: 1.570796326794897
    pitch: 0
    yaw: 0

fr3_joint5:
  kinematic:
    x: -0.0825
    y: 0.384
    z: 0
    roll: -1.570796326794897
    pitch: 0
    yaw: 0

fr3_joint6:
  kinematic:
    x: 0
    y: 0
    z: 0
    roll: 1.570796326794897
    pitch: 0
    yaw: 0

fr3_joint7:
  kinematic:
    x: 0.088
    y: 0
    z: 0
    roll: 1.570796326794897
    pitch: 0
    yaw: 0

# Joint to tool origin
fr3_joint8:
  kinematic:
    x: 0
    y: 0
    z: 0.107
    roll: 0
    pitch: 0
    yaw: 0