# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    linear_guide_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

linear_guide_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

linear_guide_scaled_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["linear_guide_speed_ovr","safe_ovr","speed_ovr"]
    allow_nonzero_velocity_at_trajectory_end: false