# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

linear_guide_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity