# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    linear_guide_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    ur_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    ur_on_linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur_on_linear_guide_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    robotiq_action_controller:
      type: position_controllers/GripperActionController

    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

    robotiq_forward_controller:
      type: robotiq_controllers/RobotiqForwardCommandController

    linear_guide_position_forward_controller:
      type: position_controllers/JointGroupPositionController

    linear_guide_string_velocity_position_controller:
      type: string_velocity_position_controller/StringVelocityPositionController

    linear_guide_string_continuous_velocity_position_controller:
      type: string_velocity_position_controller/StringVelocityPositionController

linear_guide_position_forward_controller:
  ros__parameters:
    joints:
      - guide_linear_joint

linear_guide_string_velocity_position_controller:
  ros__parameters:
    joint_name: "guide_linear_joint"
    joint_limits: [0.0,1.0]
    velocity_command_topic: "/hand_distance"
    speed_mapping:
      - left
      - "-2.3"
      - "1.5" #seconds to reset speed 
      - right
      - "2.3"
      - "1.5" #seconds to reset speed
      - down
      - "0"
      - "0.001" #seconds to reset speed
    velocity_threshold: 0.05

linear_guide_string_continuous_velocity_position_controller:
  ros__parameters:
    joint_name: "guide_linear_joint"
    joint_limits: [0.0,1.0]
    velocity_command_topic: "/hand_distance"
    speed_mapping:
      - left
      - "-0.25"
      - "100000000" #seconds to reset speed 
      - right
      - "0.25"
      - "100000000" #seconds to reset speed
      - down
      - "0"
      - "0.001" #seconds to reset speed
    velocity_threshold: 0.05

linear_guide_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

linear_guide_scaled_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["linear_guide_speed_ovr","safe_ovr","speed_ovr"]
    allow_nonzero_velocity_at_trajectory_end: false

ur_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

ur_scaled_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["ur_speed_ovr","safe_ovr","speed_ovr"]
    allow_nonzero_velocity_at_trajectory_end: false

ur_on_linear_guide_controller:
  ros__parameters:
    joints:
      - guide_linear_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

ur_on_linear_guide_scaled_controller:
  ros__parameters:
    joints:
      - guide_linear_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["ur_on_linear_guide_speed_ovr","safe_ovr","speed_ovr"]
    allow_nonzero_velocity_at_trajectory_end: false

robotiq_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    joint: robotiq_85_left_knuckle_joint
    max_effort: 0.0
    stall_timeout: 5.0
    stall_velocity_threshold: 0.001

robotiq_activation_controller:
  ros__parameters:
    default: false
