# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    linear_guide_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    ur_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    ur_on_linear_guide_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur_on_linear_guide_scaled_controller:
      type: scaled_fjt_controller/ScaledFjtController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    robotiq_action_controller:
      type: position_controllers/GripperActionController

    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

    robotiq_forward_controller:
      type: robotiq_controllers/RobotiqForwardCommandController

linear_guide_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

linear_guide_scaled_controller:
  ros__parameters:
    joints: 
      - guide_linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["linear_guide_speed_ovr","safe_ovr"]

ur_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

ur_scaled_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["ur_speed_ovr","safe_ovr"]

ur_on_linear_guide_controller:
  ros__parameters:
    joints:
      - guide_linear_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

ur_on_linear_guide_scaled_controller:
  ros__parameters:
    joints:
      - guide_linear_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
    speed_ovr_topics: ["ur_on_linear_guide_speed_ovr","safe_ovr"]

robotiq_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    joint: robotiq_85_left_knuckle_joint
    max_effort: 0.0
    stall_timeout: 10.0
    stall_velocity_threshold: 0.001

robotiq_activation_controller:
  ros__parameters:
    default: false


robotiq_forward_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    interface_names: ['position']