# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_execution:
  execution_duration_monitoring: false

moveit_simple_controller_manager:
  controller_names:
    - linear_guide_controller
    - linear_guide_scaled_controller

  linear_guide_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - guide_linear_joint
  
  linear_guide_scaled_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - guide_linear_joint