controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - linear_joint
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

#    action_monitor_rate: 20.0

#    allow_partial_joints_goal: true
#    open_loop_control: false
#    constraints:
#      stopped_velocity_tolerance: 0.01
#      goal_time: 0.0
#      joint_0:
#        trajectory: 0.05
#        goal: 0.03
#      joint_1:
#        trajectory: 0.05
#        goal: 0.03

#    gains:
#      joint_0:
#        p: 2.0
#        i: 0.0
#        d: 0.0
#        i_clamp: 30000.0
#        ff_velocity_scale: 0.1
#      joint_1:
#        p: 2.0
#        i: 0.0
#        d: 0.0
#        i_clamp: 30000.0
#        ff_velocity_scale: 0.1